name: CI_action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 20.x] # Use Node.js 16 and 20

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3  # Updated to v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install backend dependencies
      run: |
        cd backend
        npm install

    - name: Run backend tests
      run: |
        cd backend
        npm test

    - name: Build backend
      run: |
        cd backend
        npm run build
